name: "Test Fx Integration"

on: 
  push:
    paths: 
      - 'testfx/**'
      #- '.github/workflows/testfx.cd.yaml'
      #- '.github/workflows/multi-target-lib-ci.yaml'
    tags-ignore:
      - '*'
    branches-ignore:
      - 'main'

jobs:
  testfx-cd:
    uses: ./.github/workflows/multi-target-lib-ci.yaml
    with:
        project-dir: "testfx"
        project-name: "testfx"
    secrets: inherit